export const GET_CONCILIACION_MERCADOPAGO = 'modules/tesoreria/GET_CONCILIACION_MERCADOPAGO';
export const GET_CONCILIACION_MERCADOPAGO_EXCEL = 'modules/tesoreria/GET_CONCILIACION_MERCADOPAGO_EXCEL';
