export const GET_SOLICITUD_RECLAMACION = 'modules/tesoreria/GET_SOLICITUD_RECLAMACION';
export const GET_OBTENER_CATALOGOS = 'modules/tesoreria/GET_OBTENER_CATALOGOS';
export const GET_OBTENER_DISTRIBUIDORA = 'modules/tesoreria/GET_OBTENER_DISTRIBUIDORA';
export const GET_GRABAR_DISTRIBUIDORA = 'modules/tesoreria/GET_GRABAR_DISTRIBUIDORA';
